### ISSUE TITLE
[Suggestion] Most Vibrant Color

### ISSUE THREAD

**Issue by BossDaily** [Amaru8/Cider-AdaptiveAccentsEverywhere#2]
I really like the idea of this plugin but one thing I would like is a mode that selects the most vibrant color in the album art. 
Here is a [npm package](https://github.com/Vibrant-Colors/node-vibrant) that does this.

**Comment by Amaru8** [comment]
Hey~
I've been using the plugin since the release in my personal instance too and with 99% of songs it managed to figure out a good color.

However, I'll check out the package you sent when I have some free time. I don't know if you tried, but my only concern is that if immersive background is used for the app (where the artwork is morphed and set as a moving background for the app), this new logic might always return the same color as the background, which will always trigger the contrast check and result in a worse experience.

Until then, I would suggest experimenting with the plugin's settings, you might be able to figure out something which works better for your song library (as the defaults are just based on my experience).

**Comment by Amaru8** [comment]
Implemented in [v1.1.0](https://marketplace.cider.sh/plugins/23/versions/1.1.0). Customization options are available in the plugin settings. Just so you know, the default scheme option will be changed from Inverted to Generic in the next release. If you find any issues with the internal algorithm, please make a new issue here.
